# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # hhvm
  #- hhvm

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
before_script:
  # - echo "extension = gmp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --no-interaction
  - mkdir -p build/logs

script:
  - vendor/phpunit/phpunit/phpunit --configuration phpunit.travis.xml --coverage-clover build/logs/clover.xml

after_success:
    - php vendor/bin/coveralls -v
    - CODECLIMATE_REPO_TOKEN=4bb5e11a781e977d22fb5b2209b45a08e383a7671524d73b5a12f1424d91c645 ./vendor/bin/test-reporter

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "ashley@zf4.biz"